server:
   port: 9527

spring:
   application: 
      name: springcloud-zuul-gateway
      
eureka: 
   client:    #客户端注册如eureka服务列表
      service-url: 
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
      instance-id: gateway-9527.com   #默认服务名称修改,必须同时修改host文件
      prefer-ip-address: true           #访问路径可以显示ip
#使用代理，配置路由访问映射
zuul:
   prefix: /ztx                                 #设置统一的访问前缀
   ignored-services: "*"                        #关闭所有微服务正是名称的访问
   #ignored-services: provider-dept              #关闭单个微服务真实名称访问
   routes:
      mydept.serviceId: provider-dept            #真实微服务的名称
      mydept.path: /mydept/**                    #代理后名称  
info:
   app.name: springcloud-provider-dept
   company.name: www.ztx.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$